import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "@/components/Header";
import { IconMessage } from "@tabler/icons-react";
import LoginButton from "@/components/auth/Login";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-6 flex justify-center gap-2">
        <LoginButton />
        <Link href="/chat" className="btn-primary btn">
          <IconMessage /> Start Chatting!
        </Link>
      </main>
    </>
  );
};

export default Home;
